name: Notify on push to main

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Push to Master branch'
          body: 'A push has been made to the master branch of your repository.'
          to: 'javier.morales@proservicio.com'
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true
